sudo: required
language: generic
services: docker

branches:
  only:
    - master

script:
  - docker pull dxjoke/tectonic-docker
  - docker run -v $TRAVIS_BUILD_DIR/specs/anoncreds2:/tex -w /tex dxjoke/tectonic-docker /bin/sh -c "tectonic anoncreds2.tex"
